version: '3.5'

volumes:
  -pgdata:

services:
  postgres:
    profiles: [web_api]
    container_name: "mera_capital.postgres"
    image: postgres:15-alpine
    restart: unless-stopped

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ${HOME}/pgdata:/var/lib/postgresql/mera_capital_data

  # web_api:
  #   profiles: [web_api]
  #   container_name: "tender.web_api"
  #   depends_on:
  #     - postgres
  #   restart: unless-stopped

  #   build:
  #     context: ./
  #     dockerfile: ./Dockerfile
  #     target: web_api

  #   ports:
  #     - "8000:8000"
