"""initial

Revision ID: bce913ad1757
Revises:
Create Date: 2024-10-30 01:53:49.770454

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bce913ad1757"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currency",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "ticker",
            postgresql.ENUM("BTC", "ETH", name="ticker"),
            nullable=True,
        ),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("createad_at", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("currency")
    # ### end Alembic commands ###
    op.execute("DROP TYPE ticker;")
